name: Exakat

on: [push]

jobs:
  laravel-analytics:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: setup exakat
      run: docker pull exakat/exakat
    - name: analytics
      run: docker run -v $(pwd):/usr/src/exakat/projects/webapp --rm exakat/exakat exakat project - p webapp
    
